version: '3.7'
networks:
  pvdnet:
    driver: bridge
    name: pvdnet
services:
  promalaria-postgres:
    image: postgres:latest
    container_name: promalaria-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - pvdnet
  promalaria-views-api:
    build: .
    container_name: promalaria-views-api
    restart: always
    networks:
      - pvdnet
    depends_on:
      - promalaria-postgres
    ports:
      - 8889:8889
    volumes:
      - ./data:/app/data
  promalaria-dash:
    build: ./dash
    container_name: promalaria-dash
    restart: always
    networks:
      - pvdnet
