CREATE TABLE IF NOT EXISTS "Sivep" (
  "uid"           INTEGER,
  "ano"           INTEGER NOT NULL,
  "cod_noti"      INTEGER,
  "dt_notif"      TIMESTAMP(3),
  "dt_envlo"      TIMESTAMP(3),
  "dt_digit"      TIMESTAMP(3),
  "sem_noti"      DOUBLE PRECISION,
  "tipo_lam"      TEXT,
  "uf_notif"      TEXT,
  "mun_noti"      INTEGER,
  "cod_unin"      DOUBLE PRECISION,
  "cod_agen"      DOUBLE PRECISION,
  "dt_nasci"      TIMESTAMP(3),
  "id_pacie"      DOUBLE PRECISION,
  "id_dimea"      TEXT,
  "sexo"          TEXT,
  "raca"          TEXT,
  "pais_res"      TEXT,
  "uf_resid"      TEXT,
  "mun_resi"      DOUBLE PRECISION,
  "loc_resi"      DOUBLE PRECISION,
  "sintomas"      TEXT,
  "dt_sinto"      TIMESTAMP(3),
  "cod_ocup"      TEXT,
  "uf_infec"      TEXT,
  "pais_inf"      TEXT,
  "mun_infe"      DOUBLE PRECISION,
  "loc_infe"      DOUBLE PRECISION,
  "dt_exame"      TIMESTAMP(3),
  "res_exam"      TEXT,
  "qtd_para"      DOUBLE PRECISION,
  "qtd_cruz"      TEXT,
  "dt_trata"      TIMESTAMP(3),
  "esquema"       TEXT,
  "hemoparasi"    TEXT,
  "exame"         TEXT,
  "examinador"    TEXT,
  "id_lvc"        TEXT,
  "gestante"      TEXT,
  "vivax"         TEXT,
  "falciparum"    TEXT,
  "niv_esco"      TEXT,
  "id_pacie_anos" INTEGER,
  "nu_predi_infe" DOUBLE PRECISION,
  "nu_habit_infe" DOUBLE PRECISION,
  "zona_infe"     TEXT,
  "categori_infe" TEXT,
  "nu_predi_resi" DOUBLE PRECISION,
  "nu_habit_resi" DOUBLE PRECISION,
  "zona_resi"     TEXT,
  "categori_resi" TEXT
) PARTITION BY LIST ("ano");
