name: Malaria Views (dev)

on:
  push:
    branches: [develop]
  workflow_dispatch:

env:
  NODE_VERSION: 20.8.0
  SERVER_PRIVATE_KEY: ${{ secrets.DEV_SERVER_PRIVATE_KEY }}
  SERVER_USER: ${{ secrets.DEV_SERVER_USER }}
  SERVER_HOST: ${{ secrets.DEV_SERVER_HOST }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_IMAGE }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup deploy script
        run: |
          cat <<EOF > deploy
            #!/bin/bash
            echo "$DEV_SERVER_PRIVATE_KEY" > private_key;
            chmod 600 private_key;

            mkdir tmp-deploy;
            cp -rf dist tmp-deploy/.;
            cp -rf dash tmp-deploy/.;
            cp -rf Dockerfile tmp-deploy/.;
            cp -rf docker-compose.yml tmp-deploy/.;
            tar czf dist.tgz tmp-deploy/;

            ssh -o StrictHostKeyChecking=no -i private_key \
              $DEV_SERVER_USER@$DEV_SERVER_HOST "mkdir -p /home/$DEV_SERVER_USER/promalaria-backend;"

            scp -o StrictHostKeyChecking=no -i private_key \
              dist.tar.gz $DEV_SERVER_USER@$DEV_SERVER_HOST:/home/$DEV_SERVER_USER/promalaria-backend/dist.tgz;

            ssh -o StrictHostKeyChecking=no -i private_key $DEV_SERVER_USER@$DEV_SERVER_HOST "
              cd /home/$DEV_SERVER_USER/promalaria-backend;
              rm -rf dash;
              rm -rf dist;
              rm package*.json;
              rm Dockerfile;
              rm docker-compose.yml;
              tar -xzvf dist.tgz;
              mv tmp-deploy/* .;
              rm -rf tmp-deploy;
              rm dist.tgz;

              docker-compose rm -sf promalaria-postgres promalaria-backend promalaria-dash;
              yes | docker builder prune -f;

              docker-compose up -d --build promalaria-postgres;
              docker-compose up -d --build promalaria-backend;
              docker-compose up -d --build promalaria-dash;
            "
          EOF
          chmod +x deploy
      - name: Run deploy script
        run: ./deploy
