name: Malaria Views

on:
  push:
    branches: [prod]
  workflow_dispatch:

env:
  NODE_VERSION: 20.8.0
  SERVER_PASSWORD: ${{ secrets.PROD_SERVER_PASSWORD }}
  SERVER_USER: ${{ secrets.PROD_SERVER_USER }}
  SERVER_HOST: ${{ secrets.PROD_SERVER_HOST }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_IMAGE }}
      - name: Install sshpass
        run: sudo apt install -y sshpass
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup deploy script
        run: |
          cat <<EOF > deploy
            #!/bin/bash
            echo "" > private_key;
            chmod 600 private_key;

            mkdir tmp-deploy;
            cp -rf dist tmp-deploy/.;
            cp -rf dash tmp-deploy/.;
            cp -rf Dockerfile tmp-deploy/.;
            cp -rf docker-compose.yml tmp-deploy/.;
            tar czf dist.tgz tmp-deploy/;

            sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no \
              $SERVER_USER@$SERVER_HOST "mkdir -p /home/$SERVER_USER/promalaria-backend;"

            sshpass -p "$SERVER_PASSWORD" scp -o StrictHostKeyChecking=no \
              dist.tar.gz $SERVER_USER@$SERVER_HOST:/home/$SERVER_USER/promalaria-backend/dist.tgz;

            sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "
              cd /home/$SERVER_USER/promalaria-backend;
              rm -rf dash;
              rm -rf dist;
              rm package*.json;
              rm Dockerfile;
              rm docker-compose.yml;
              tar -xzvf dist.tgz;
              mv tmp-deploy/* .;
              rm -rf tmp-deploy;
              rm dist.tgz;

              docker-compose rm -sf promalaria-postgres promalaria-backend promalaria-dash;
              yes | docker builder prune -f;

              docker-compose up -d --build promalaria-postgres;
              docker-compose up -d --build promalaria-backend;
              docker-compose up -d --build promalaria-dash;
            "
          EOF
          chmod +x deploy
      - name: Run deploy script
        run: ./deploy
